[package]
org = "nidula"
name = "aegis_disaster_alert"
version = "0.1.0"
distribution = "2201.12.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "4.0.0"
